import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/components/themes/theme-provider";
import TopNav from "@/components/layout/top-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container mx-auto my-5 relative">
            <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
              <header>
                <TopNav />
              </header>

              <main>
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
