import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import { ThemeProvider } from "@/components/themes/theme-provider";
import TopNav from "@/components/layout/top-nav";
import { Card } from "@/components/ui/card";


export const metadata: Metadata = {
  title: "Ald - Prototype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container mx-auto my-5 relative">
            <Card>
              <header>
                <TopNav />
              </header>

              <main className="flex-1">
                <div className="flex-1 space-y-4 p-8 pt-6">
                  {children}
                </div>
              </main>
            </Card>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
